title: Vishnu - logical monitoring job-controller

description: > # this means to ignore newlines until "baseurl:"
  

# Production
# # absoluteurl: "https://vishnuhome.github.io/Vishnu"
baseurl: "/Vishnu" # the subpath of the site on https://vishnuhome.github.io/Vishnu
url: "https://vishnuhome.github.io/Vishnu" # the base hostname & protocol for your site

# local Testing
# baseurl: "" # the subpath of the site for local testing on http://localhost:4000
# url: "http://localhost:4000" # the base hostname & protocol for your site

# online Testing
# baseurl: "/underConstruction" # the subpath of the site for online Testing on https://readybin.github.io/underConstruction
# url: "https://readybin.github.io/underConstruction" # the base hostname & protocol for your site

keywords: ["Vishnu", "monitoring", "monitor", "Überwachung", "überwachen", "plugin", "parallel", "Prozesssteuerung", "Steuerung", "process", "job-controller", "controlling", "windows", "desktop", "c#", "github", "open source", "kostenlos", "free", "Erik", "Nagel", "vishnu@reallyhuman.net"]

# theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
